before:
  hooks:
    - go mod tidy
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goamd64: v4
    mod_timestamp: "{{ .CommitTimestamp }}"

#universal_binaries:
#  - replace: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- tolower .Os }}-
      {{- .Arch }}
    rlcp: true
    files:
      - "!*"

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- tolower .Os }}-
      {{- .Arch }}
    id: packages
    homepage: https://local-deploy.github.io
    description: |-
      Deploy Local — site deployment assistant locally.
      A convenient wrapper over docker-compose, which simplifies the local deployment of the project.
    maintainer: Sergey Voloshin <dl@varme.pw>
    license: MIT
    vendor: DeployLocal
    section: utils
    formats:
      - deb
    #  - rpm
    #  - archlinux
    dependencies:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    scripts:
      preinstall: "./.github/scripts/packages/preinstall.sh"
    contents:
      - src: config-files/
        dst: /etc/dl/config-files
      - src: .github/scripts/packages/completions/zsh
        dst: /usr/share/zsh/vendor-completions/_dl
      - src: .github/scripts/packages/completions/bash
        dst: /usr/share/bash-completion/completions/dl
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - 'FURY_TOKEN={{ .Env.FURY_TOKEN }}'
    cmd: ./.github/scripts/fury-upload.sh {{ .ArtifactName }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
