name: Feature request
description: Missing functionality? Come tell us about it!
labels: [ 'enhancement' ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the feature you want to see?
    validations:
      required: true
