services:
  postgres:
    container_name: ${HOST_NAME}_pgsql
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      - "POSTGRES_DB=${POSTGRES_DB:-db}"
      - "POSTGRES_USER=${POSTGRES_USER:-db}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-db}"
      - "PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}"
    volumes:
      - "${PWD}/.docker/volume/pg/:/var/lib/postgresql/data/:delegated"
